import type { Metadata } from "next";
import { FC, ReactNode } from "react";
import "./globals.css";

interface Props {
  children: ReactNode;
}


export const metadata: Metadata = {
  title: "Cake Order App",
  description: "Generated by create next app",
};

const RootLayout:FC<Props> = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) =>(
    <html lang="en">
      <body>
        {children}

      </body>
    </html>
  );


export default RootLayout;
